<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction-to-Numpy" data-toc-modified-id="Introduction-to-Numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction to Numpy</a></span><ul class="toc-item"><li><span><a href="#What-is-Numpy?" data-toc-modified-id="What-is-Numpy?-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>What is Numpy?</a></span></li><li><span><a href="#Why-Use-NumPy?" data-toc-modified-id="Why-Use-NumPy?-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Why Use NumPy?</a></span></li><li><span><a href="#Why-is-NumPy-Faster-Than-Lists?" data-toc-modified-id="Why-is-NumPy-Faster-Than-Lists?-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Why is NumPy Faster Than Lists?</a></span></li><li><span><a href="#Which-Language-is-NumPy-written-in?" data-toc-modified-id="Which-Language-is-NumPy-written-in?-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Which Language is NumPy written in?</a></span></li><li><span><a href="#Where-is-the-NumPy-Codebase?" data-toc-modified-id="Where-is-the-NumPy-Codebase?-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Where is the NumPy Codebase?</a></span></li></ul></li><li><span><a href="#Installing-NumPy" data-toc-modified-id="Installing-NumPy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Installing NumPy</a></span></li><li><span><a href="#Getting-Started" data-toc-modified-id="Getting-Started-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Getting Started</a></span><ul class="toc-item"><li><span><a href="#Import-NumPy" data-toc-modified-id="Import-NumPy-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Import NumPy</a></span></li><li><span><a href="#NumPy-as-np" data-toc-modified-id="NumPy-as-np-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>NumPy as np</a></span></li><li><span><a href="#Checking-NumPy-Version" data-toc-modified-id="Checking-NumPy-Version-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Checking NumPy Version</a></span></li></ul></li><li><span><a href="#NumPy-Creating-Arrays" data-toc-modified-id="NumPy-Creating-Arrays-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>NumPy Creating Arrays</a></span><ul class="toc-item"><li><span><a href="#Create-a-NumPy-ndarray-Object" data-toc-modified-id="Create-a-NumPy-ndarray-Object-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Create a NumPy ndarray Object</a></span></li><li><span><a href="#Dimensions-in-Arrays" data-toc-modified-id="Dimensions-in-Arrays-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>Dimensions in Arrays</a></span><ul class="toc-item"><li><span><a href="#0-D-Arrays" data-toc-modified-id="0-D-Arrays-4.2.1"><span class="toc-item-num">4.2.1&nbsp;&nbsp;</span>0-D Arrays</a></span></li><li><span><a href="#1-D-Arrays" data-toc-modified-id="1-D-Arrays-4.2.2"><span class="toc-item-num">4.2.2&nbsp;&nbsp;</span>1-D Arrays</a></span></li><li><span><a href="#2-D-Arrays" data-toc-modified-id="2-D-Arrays-4.2.3"><span class="toc-item-num">4.2.3&nbsp;&nbsp;</span>2-D Arrays</a></span></li><li><span><a href="#3-D-arrays" data-toc-modified-id="3-D-arrays-4.2.4"><span class="toc-item-num">4.2.4&nbsp;&nbsp;</span>3-D arrays</a></span></li></ul></li><li><span><a href="#Check-Number-of-Dimensions?" data-toc-modified-id="Check-Number-of-Dimensions?-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Check Number of Dimensions?</a></span></li><li><span><a href="#Higher-Dimensional-Arrays" data-toc-modified-id="Higher-Dimensional-Arrays-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Higher Dimensional Arrays</a></span></li></ul></li><li><span><a href="#NumPy-Array-Indexing" data-toc-modified-id="NumPy-Array-Indexing-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>NumPy Array Indexing</a></span><ul class="toc-item"><li><span><a href="#Access-Array-Elements" data-toc-modified-id="Access-Array-Elements-5.1"><span class="toc-item-num">5.1&nbsp;&nbsp;</span>Access Array Elements</a></span></li><li><span><a href="#Access-2-D-Arrays" data-toc-modified-id="Access-2-D-Arrays-5.2"><span class="toc-item-num">5.2&nbsp;&nbsp;</span>Access 2-D Arrays</a></span></li><li><span><a href="#Access-3-D-Arrays" data-toc-modified-id="Access-3-D-Arrays-5.3"><span class="toc-item-num">5.3&nbsp;&nbsp;</span>Access 3-D Arrays</a></span></li><li><span><a href="#Negative-Indexing" data-toc-modified-id="Negative-Indexing-5.4"><span class="toc-item-num">5.4&nbsp;&nbsp;</span>Negative Indexing</a></span></li></ul></li><li><span><a href="#NumPy-Array-Slicing" data-toc-modified-id="NumPy-Array-Slicing-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>NumPy Array Slicing</a></span><ul class="toc-item"><li><span><a href="#Slicing-arrays" data-toc-modified-id="Slicing-arrays-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Slicing arrays</a></span></li><li><span><a href="#Negative-Slicing" data-toc-modified-id="Negative-Slicing-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Negative Slicing</a></span></li><li><span><a href="#STEP" data-toc-modified-id="STEP-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>STEP</a></span></li><li><span><a href="#Slicing-2-D-Arrays" data-toc-modified-id="Slicing-2-D-Arrays-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>Slicing 2-D Arrays</a></span></li></ul></li><li><span><a href="#NumPy-Data-Types" data-toc-modified-id="NumPy-Data-Types-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>NumPy Data Types</a></span><ul class="toc-item"><li><span><a href="#Data-Types-in-Python" data-toc-modified-id="Data-Types-in-Python-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>Data Types in Python</a></span></li><li><span><a href="#Data-Types-in-NumPy" data-toc-modified-id="Data-Types-in-NumPy-7.2"><span class="toc-item-num">7.2&nbsp;&nbsp;</span>Data Types in NumPy</a></span></li><li><span><a href="#Checking-the-Data-Type-of-an-Array" data-toc-modified-id="Checking-the-Data-Type-of-an-Array-7.3"><span class="toc-item-num">7.3&nbsp;&nbsp;</span>Checking the Data Type of an Array</a></span></li><li><span><a href="#What-if-a-Value-Can-Not-Be-Converted?" data-toc-modified-id="What-if-a-Value-Can-Not-Be-Converted?-7.4"><span class="toc-item-num">7.4&nbsp;&nbsp;</span>What if a Value Can Not Be Converted?</a></span></li></ul></li><li><span><a href="#References" data-toc-modified-id="References-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>References</a></span></li><li><span><a href="#Other-Links" data-toc-modified-id="Other-Links-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>Other Links</a></span></li></ul></div>

# Introduction to Numpy
<img src="./numpylogo.svg" width="500" height="500">

## What is Numpy?
NumPy was created in 2005 by **Travis Oliphant**. It is an **open source** project and you can use it freely. It is the fundamental package for **scientific computing** in Python. It is a Python **library** that provides a **multidimensional array object**, various derived objects (such as masked arrays and matrices), and an assortment of routines for **fast operations on arrays**, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the **ndarray object**. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important **differences between NumPy arrays and the standard Python sequences**:

<ul>
    <li>NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.</li>
    <li>The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.</li>
    <li>NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.</li>
    <li>A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.</li>
</ul>


## Why Use NumPy?
In Python we have **lists** that serve the purpose of arrays, but they are **slow to process**.
NumPy aims to provide an array object that is up to **50x faster** than traditional Python lists.
The array object in NumPy is called **`ndarray`**, it provides a lot of supporting functions that make working with `ndarray` very easy.
Arrays are very frequently used in data science, where speed and resources are very important.

## Why is NumPy Faster Than Lists?
NumPy arrays are stored at **one continuous place in memory** unlike lists, so processes can access and manipulate them very efficiently.
This behavior is called **locality of reference** in computer science.
This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## Which Language is NumPy written in?
NumPy is a Python library and is written partially in **Python**, but most of the parts that require fast computation are written in **C** or **C++**.

## Where is the NumPy Codebase?
The source code for NumPy is located at this github repository https://github.com/numpy/numpy

# Installing NumPy
The only prerequisite for installing NumPy is Python itself. If you don’t have Python yet and want the simplest way to get started, we recommend you use the `Anaconda Distribution` - it includes Python, NumPy, and many other commonly used packages for scientific computing and data science.

NumPy can be installed with `conda`, `pip` with a package manager on macOS and Linux, or [from source](https://numpy.org/devdocs/user/building.html).

```python
> pip install numpy
```

# Getting Started
## Import NumPy
Once NumPy is installed, import it in your applications by adding the `import` keyword:


```python
import numpy
```

In [1]:
import numpy

In [2]:
arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## NumPy as np
NumPy is usually imported under the `np` alias.

Create an alias with the `as` keyword while importing:
```python
import numpy as np
```

In [3]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## Checking NumPy Version
The version string is stored under `__version__` attribute.

```python
np.__version__
```

In [5]:
print(np.__version__)

1.23.1


# NumPy Creating Arrays
## Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called `ndarray`.

We can create a NumPy `ndarray` object by using the `array()` function.

```python
np.array()
```

In [6]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an `ndarray`, we can pass a list, tuple or any array-like object into the `array()` method, and it will be converted into an ndarray:

In [7]:
lst = [1, 2, 3, 4]
arr = np.array(lst)

print(arr)
print(type(arr))
print(type(lst))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'list'>


## Dimensions in Arrays
A dimension in arrays is one level of array depth (nested arrays).

Nested array: are arrays that have arrays as their elements.

### 0-D Arrays
0-D arrays, or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [8]:
arr = np.array(42)

print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


### 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [9]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


### 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

`NumPy has a whole sub module dedicated towards matrix operations called numpy.mat`

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [11]:
matrix = np.mat([[1, 2, 3], [4, 5, 6]])

print(matrix)
print(type(matrix))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


### 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
print(type(arr))

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>


## Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [13]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


## Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the `ndmin` argument.

In [14]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In this array the innermost dimension (5th dim) has 4 elements, the 4th dim has 1 element that is the vector, the 3rd dim has 1 element that is the matrix with the vector, the 2nd dim has 1 element that is 3D array and 1st dim has 1 element that is a 4D array.

# NumPy Array Indexing
## Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [17]:
arr = np.array([1, 2, 3, 4])

print(arr[0]) # Get the first element
print(arr[1]) # Get the second element
print(arr[2] + arr[3]) # Get third and fourth elements from the following array and add them

1
2
7


## Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.

In [19]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr, '\n')
print('2nd element on 1st row: ', arr[0, 1]) # Access the element on the first row, second column

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

2nd element on 1st row:  2


In [20]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr, '\n')
print('5th element on 2nd row: ', arr[1, 4]) # Access the element on the 2nd row, 5th column

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

5th element on 2nd row:  10


## Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [21]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr, '\n')
print(arr[0, 1, 2]) # Access the third element of the second array of the first array

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

6


## Negative Indexing
Use negative indexing to access an array from the end.

In [22]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print(arr, '\n')
print('Last element from 2nd dim: ', arr[1, -1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

Last element from 2nd dim:  10


# NumPy Array Slicing
## Slicing arrays
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

**Note: The result includes the start index, but excludes the end index.**

In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr, '\n')
print(arr[1:5]) # Slice elements from index 1 to index 5 from the following array

[1 2 3 4 5 6 7] 

[2 3 4 5]


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr, '\n')
print(arr[4:]) # Slice elements from index 4 to the end of the array

[1 2 3 4 5 6 7] 

[5 6 7]


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr, '\n')
print(arr[:4]) # Slice elements from the beginning to index 4 (not included)

[1 2 3 4 5 6 7] 

[1 2 3 4]


## Negative Slicing
Use the minus operator to refer to an index from the end:

In [26]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr, '\n')
print(arr[-3:-1]) # Slice from the index 3 from the end to index 1 from the end

[1 2 3 4 5 6 7] 

[5 6]


## STEP
Use the `step` value to determine the step of the slicing:

In [27]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr, '\n')
print(arr[1:5:2]) # Return every other element from index 1 to index 5

[1 2 3 4 5 6 7] 

[2 4]


In [28]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr, '\n')
print(arr[::2]) # Return every other element from the entire array

[1 2 3 4 5 6 7] 

[1 3 5 7]


## Slicing 2-D Arrays

In [29]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr, '\n')
print(arr[1, 1:4]) # From the second element, slice elements from index 1 to index 4 (not included)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

[7 8 9]


**Note: Remember that second element has index 1.**

In [30]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr, '\n')
print(arr[0:2, 2]) # From both elements, return index 2

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

[3 8]


In [31]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr, '\n')
print(arr[0:2, 1:4]) # From both elements, slice index 1 to index 4 (not included), this will return a 2-D array

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

[[2 3 4]
 [7 8 9]]


# NumPy Data Types
## Data Types in Python
By default Python have these data types:

<ul>
    <li><code>strings</code> - used to represent text data, the text is given under quote marks. e.g. "ABCD"</li>
    <li><code>integer</code> - used to represent integer numbers. e.g. -1, -2, -3</li>
    <li><code>float</code> - used to represent real numbers. e.g. 1.2, 42.42</li>
    <li><code>boolean</code> - used to represent True or False.</li>
    <li><code>complex</code> - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j</li>
</ul>


## Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like `i` for integers, `u` for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

<ul>
    <li><code>i</code> - integer</li>
    <li><code>b</code> - boolean</li>
    <li><code>u</code> - unsigned integer</li>
    <li><code>f</code> - float</li>
    <li><code>c</code> - complex float</li>
    <li><code>m</code> - timedelta</li>
    <li><code>M</code> - datetime</li>
    <li><code>O</code> - object</li>
    <li><code>S</code> - string</li>
    <li><code>U</code> - unicode string</li>
    <li><code>V</code> - fixed chunk of memory for other type ( void )</li>
</ul>

## Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [32]:
arr = np.array([1, 2, 3, 4])

print(arr, '\n')
print(arr.dtype) # Get the data type of an array object

[1 2 3 4] 

int32


In [33]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr, '\n')
print(arr.dtype) # Get the data type of an array containing strings

['apple' 'banana' 'cherry'] 

<U6


## Creating Arrays With a Defined Data Type
We use the `array()` function to create arrays, this function can take an optional argument: `dtype` that allows us to define the expected data type of the array elements:

In [35]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr, '\n')
print(arr.dtype) # Create an array with data type string:

[b'1' b'2' b'3' b'4'] 

|S1


For `i`, `u`, `f`, `S` and `U` we can define size as well.

In [36]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr, '\n')
print(arr.dtype) # Create an array with data type 4 bytes integer

[1 2 3 4] 

int32


## What if a Value Can Not Be Converted?
If a type is given in which elements can't be casted then NumPy will raise a ValueError.

**ValueError:** In Python ValueError is raised when the type of passed argument to a function is unexpected/incorrect.

In [37]:
arr = np.array(['a', '2', '3'], dtype='i') # A non integer string like 'a' can not be converted to integer (will raise an error)

ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
a = [1, 2, 3]
b = [4, 5, 6]
c = a * b

for example see try code:

```python
a = [1, 2, 3]
b = [4, 5, 6]
c = a * b
```

# References
1. https://numpy.org/
2. https://www.w3schools.com/python/numpy/

# Other Links
1. https://www.youtube.com/watch?v=gFEE3w7F0ww