<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Introduction-to-Numpy" data-toc-modified-id="Introduction-to-Numpy-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Introduction to Numpy</a></span><ul class="toc-item"><li><span><a href="#What-is-Numpy?" data-toc-modified-id="What-is-Numpy?-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>What is Numpy?</a></span></li><li><span><a href="#Why-Use-NumPy?" data-toc-modified-id="Why-Use-NumPy?-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Why Use NumPy?</a></span></li><li><span><a href="#Why-is-NumPy-Faster-Than-Lists?" data-toc-modified-id="Why-is-NumPy-Faster-Than-Lists?-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Why is NumPy Faster Than Lists?</a></span></li><li><span><a href="#Which-Language-is-NumPy-written-in?" data-toc-modified-id="Which-Language-is-NumPy-written-in?-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Which Language is NumPy written in?</a></span></li><li><span><a href="#Where-is-the-NumPy-Codebase?" data-toc-modified-id="Where-is-the-NumPy-Codebase?-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Where is the NumPy Codebase?</a></span></li></ul></li><li><span><a href="#Installing-NumPy" data-toc-modified-id="Installing-NumPy-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Installing NumPy</a></span></li><li><span><a href="#Getting-Started" data-toc-modified-id="Getting-Started-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Getting Started</a></span><ul class="toc-item"><li><span><a href="#Import-NumPy" data-toc-modified-id="Import-NumPy-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>Import NumPy</a></span></li><li><span><a href="#NumPy-as-np" data-toc-modified-id="NumPy-as-np-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>NumPy as np</a></span></li><li><span><a href="#Checking-NumPy-Version" data-toc-modified-id="Checking-NumPy-Version-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>Checking NumPy Version</a></span></li></ul></li><li><span><a href="#NumPy-Creating-Arrays" data-toc-modified-id="NumPy-Creating-Arrays-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>NumPy Creating Arrays</a></span><ul class="toc-item"><li><span><a href="#Create-a-NumPy-ndarray-Object" data-toc-modified-id="Create-a-NumPy-ndarray-Object-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>Create a NumPy ndarray Object</a></span></li></ul></li><li><span><a href="#References" data-toc-modified-id="References-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>References</a></span></li><li><span><a href="#Other-Links" data-toc-modified-id="Other-Links-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Other Links</a></span></li></ul></div>

# Introduction to Numpy
<img src="./numpylogo.svg" width="500" height="500">

## What is Numpy?
NumPy was created in 2005 by **Travis Oliphant**. It is an **open source** project and you can use it freely. It is the fundamental package for **scientific computing** in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types, with many operations being performed in compiled code for performance. There are several important differences between NumPy arrays and the standard Python sequences:

<ul>
    <li>NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.</li>
    <li>The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory. The exception: one can have arrays of (Python, including NumPy) objects, thereby allowing for arrays of different sized elements.</li>
    <li>NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.</li>
    <li>A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays. In other words, in order to efficiently use much (perhaps even most) of today’s scientific/mathematical Python-based software, just knowing how to use Python’s built-in sequence types is insufficient - one also needs to know how to use NumPy arrays.</li>
</ul>


## Why Use NumPy?
In Python we have **lists** that serve the purpose of arrays, but they are **slow to process**.
NumPy aims to provide an array object that is up to **50x faster** than traditional Python lists.
The array object in NumPy is called **`ndarray`**, it provides a lot of supporting functions that make working with `ndarray` very easy.
Arrays are very frequently used in data science, where speed and resources are very important.

## Why is NumPy Faster Than Lists?
NumPy arrays are stored at **one continuous place in memory** unlike lists, so processes can access and manipulate them very efficiently.
This behavior is called **locality of reference** in computer science.
This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## Which Language is NumPy written in?
NumPy is a Python library and is written partially in **Python**, but most of the parts that require fast computation are written in **C** or **C++**.

## Where is the NumPy Codebase?
The source code for NumPy is located at this github repository https://github.com/numpy/numpy

# Installing NumPy
The only prerequisite for installing NumPy is Python itself. If you don’t have Python yet and want the simplest way to get started, we recommend you use the `Anaconda Distribution` - it includes Python, NumPy, and many other commonly used packages for scientific computing and data science.

NumPy can be installed with `conda`, `pip` with a package manager on macOS and Linux, or [from source](https://numpy.org/devdocs/user/building.html).

```python
> pip install numpy
```

# Getting Started
## Import NumPy
Once NumPy is installed, import it in your applications by adding the `import` keyword:


```python
import numpy
```

In [14]:
import numpy

In [23]:
arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## NumPy as np
NumPy is usually imported under the `np` alias.

Create an alias with the `as` keyword while importing:
```python
import numpy as np
```

In [16]:
import numpy as np

In [21]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


## Checking NumPy Version
The version string is stored under `__version__` attribute.

```python
np.__version__
```

In [18]:
print(np.__version__)

1.23.1


# NumPy Creating Arrays
## Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called `ndarray`.

We can create a NumPy `ndarray` object by using the `array()` function.

```python
np.array()
```

In [20]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


To create an `ndarray`, we can pass a list, tuple or any array-like object into the `array()` method, and it will be converted into an ndarray:

In [24]:
lst = [1, 2, 3, 4]
arr = np.array(lst)

print(arr)
print(type(arr))
print(type(lst))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'list'>


In [3]:
a = [1, 2, 3]
b = [4, 5, 6]
c = a * b

TypeError: can't multiply sequence by non-int of type 'list'

for example see try code:

```python
a = [1, 2, 3]
b = [4, 5, 6]
c = a * b
```

# References
1. https://numpy.org/
2. https://www.w3schools.com/python/numpy/

# Other Links
1. https://www.youtube.com/watch?v=gFEE3w7F0ww